[ee]
type = "service_account"
project_id = "mechakra-2003"
private_key_id = "60eb4b7c268d90aae69b2e8814c88371a0c1012e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDrfEKMu7kOg3nI
CjVK+MhEqSZDWWxiGKrKBK1k/uw4ayhs7nvB9HW8n9FxcxkUtMHoy8sdFwpVYL1Q
oUiGd8usqa69XsFRv3bNBLIaCxCF9kpKgEhE68hlvCxAAnatufiM+IlXgdQ3/wJP
T2v5mnfCAHIHpMAYU5/KUx3BLwguvoxc7RMPA4YcJ52BzcqiBqpNfP2T3PlhWAnm
OomT47IdKeGpJwRk03nPh8G+EoErumg+LjB3GwqFiV1Vl63Rp96sKZxyaOPDnGSt
sfnTqZxwu4zms37y4zyJffQOX2of9SFBdhKbsnJowGW5DL0qu8m4EeZhI285eeU+
P8ZBg8GzAgMBAAECggEASFt+sXKvOsPwZCSq2nYWR264OKKeGIhe1kNYqjtghzd6
DPq8oUzF7qcm+pa0wrWGDcutBivBu5lFoqRkPhlKRqw+6qZWfZF45idGuJTkx1z1
1+2SB0dx5LzM1gBLyjbmJh7qSK62cFxVr9wGIAS0PrLXVvzrH652X3tpnaYffAjv
AFtSKwV5zirPUrMdu7B0BjRl6pP8sxXpbZhwKnozPttQAmbXM/sYUclhnfsWFcyP
fsqDQ9gPK47/sz4Y2fnNjYVC6hF8mDfXThe2K7zobR8emtbzeUY6AWGSbmhv1g/h
Z/UDEBZjnr1u8bADQfLBD/NbIj259YaAjdbRttevaQKBgQD3m8EDxSlG52VEhMM6
/eSkS4p/5aesedoIajYmtJyryimWWG00XSgyftZ+ZjI0t5UZUvpEuLvDYr57nM4O
zodc2IG7z/WGfSRjxkV7ow5uYXqXwOF/Fp7zAkInb1nYf/Blj6TSCSjxw4PgG793
j8dcGSKGEz54XbrxTSebrmSqGQKBgQDzd1OtoD06urxd0BCZtkV7iJmfORaW72eF
/N+ufoEk1XAkMIh3opmfkU06lGX1RaqnQrDabk951q+2K/dhAw4a88oLHas1cA8R
K61zcsfWUrztklC29QdBvyyl9MA38AxEC7Cuqysb27pxuvx/KX6jtDktmU0L0XmA
wUIsprGbqwKBgQDD/cp7FH4GvLSA1uG9+SgZEB5R/FOLh2wZCxFP89irdjsS4W2X
bEGcLp/Tr0sARWxEflTRPrSJBMkoCUdlmv60dD/EjOiYisfaHh/zrG6I2qnyIt+a
/CnWyqvYkSA56ZM8oMXi5xM8wvjI1M3qcqln8hFMtUDWf8Kwq9S1OwY9SQKBgA7X
WE9+NB1PYsopM8na9ZNZOVweY8UhpOLjDlOZvI+dPy/FkZwRWmICvn1yrGBuNb/q
bdNy4/9eWem19meAgyybbdaNoXEpepGmYvVlqs7izkeBItB0UVPtrnATYmBGjsjb
GZMcNg2FsHDcYCX0Rpb+Fno0HSE6TLjPjxQfuTXvAoGBAIVBlRE9ZIJvjKq24v5E
qPU6Ej4rvYfqfyvyenwtrOTYOH5fcYt7wvGFFQSU9QIOhGMVmQjXPwYFmT0udq8K
+SrA+Gt8G0J6QVM1rMjnvugSGsC/a7LiFWgpPZzS/9xL5I0N7sbvFC7SFSA0UmK+
tbudFV7cqW0R6+2rzrNl5isT
-----END PRIVATE KEY-----"""
client_email = "ee-streamlit@mechakra-2003.iam.gserviceaccount.com"
client_id = "113379176374248075896"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ee-streamlit%40mechakra-2003.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
